uisautomation/iar-frontend

- .editorconfig
- README.md
- package.json
- src/components/LoginButton.js
- src/components/LoginRequiredRoute.js
- src/components/LogoutLink.js
- src/components/Sidebar.js
- src/components/Static.js
- src/containers/App.js
- src/containers/App.test.js
- src/containers/AssetForm.js
- src/containers/AssetList.js
- src/containers/LoginPage.js
- src/containers/LoginPage.test.js
- src/containers/Page.js
- src/index.js
- src/redux/actions/auth.js
- src/redux/actions/index.js
- src/redux/enhancer.js
- src/redux/reducers/index.js
- src/redux/store.js
- src/redux/store.test.js
- src/test/mock-localstorage.js
- src/testutils.js
Add redux-implicit-oauth2 and configure a basic sign in flow using a
redux store. The OAuth2 flow is pre-configured to make use of our
experimental OAuth2 deployment. It is left as an open question of where
central configuration information should live for the application.
See [0] for an introduction to the basics of Redux and how it is used in
React apps.
In order to render the Sign In page if the user is not logged in, the
existing Route-s are replaced with a LoginRequiredRoute which examines
the current store to determine if the user is logged in. If not, they
display the sign in page.
In order to allow the sign in page to not have a sidebar, the components
are re-jigged a little to be contained within a common "Page" component
which renders the sidebar. The LoginPage component does …
> enable sign in via OAuth2 token

- src/components/Sidebar.js
- src/containers/AppRoutes.js
- src/containers/AppRoutes.test.js
- src/containers/Static.js
- src/static/help.js
Since the re-design there is now only one static page. (And possibly
"Feedback".) Lift the content from the document cited in #11 and add
some basic styling for the page.
Static page content and titles are now defined in ES6 modules under
src/static for convenience of editing. The Static component is re-worked
to accept a page name corresponding to the module name under src/static.
Update the sidebar to link to the only static page we currently have.
Closes #11
> add help content for static page

- src/components/AssetTable.js
- src/components/AssetTableBody.js
- src/components/AssetTableBody.test.js
- src/components/AssetTableHeader.js
- src/components/AssetTableHeader.test.js
- src/containers/AssetForm.test.js
- src/containers/AssetList.js
- src/containers/AssetList.test.js
- src/redux/actions/assetRegisterApi.js
- src/redux/actions/assetRegisterApi.test.js
- src/redux/reducers/assetRegisterApi.js
- src/redux/reducers/assetRegisterApi.test.js
Add sorting to the asset list. Filtering would also be possible but there is no UI design for it yet so I've left it for another story. This is done with two commits:
e32351b adds a new action, getAssets, which fetches a new list of assets from the API with a query specifying search, sorting and filtering. When the request succeeds, the redux state is updated to record the query so that UI components can react.
78cdb60 adds some UI components which react to this change by re-factoring the AssetTable body and header into two components and making use of the new TableSortLabel component from MUI v1 to render a nice header.
**Update:** After merging current master, I found that the asset list was not correctly refreshed after asset creation. a94f955 fixes that and 8ec87da ensures that the …
> add sorting to the asset list

- src/components/AssetFormHeader.js
- src/components/AssetListHeader.js
Buttons in both headers are changed to white to contrast with the primary coloured Appbar.
Cancel button in the edit view is no longer raised.
Closes #13
> Change button colour in headers

- src/containers/AssetForm.js
- src/containers/AssetForm.test.js
The current AssetForm defaults to setting private as "null" which does not work with the current backend. Default it to "false".
Closes #47
> AssetForm: make "private" default to false

- src/components/AssetListItem.js
- src/components/FetchLookupInstitutions.js
- src/components/FetchLookupInstitutions.test.js
- src/components/Lookup.test.js
- src/components/LookupInstitution.js
- src/components/LookupInstitution.test.js
- src/containers/App.js
- src/redux/actions/lookupApi.js
- src/redux/reducers/lookupApi.js
- src/redux/reducers/lookupApi.test.js
Add a list of institutions keyed by instid to the redux store and add a
new action, listInstitutions(), which will populate it.
Add a LookupInstitution component which renders a lookup instution given
the lookup instid falling back to using the instid.
The initial fetch is triggered by a FetchLookupInstitutions component
which will cause a fetch of institutions on first render if a fetch had
not previous occurred. This component is rendered outside of the router
component since it should only fetch on first page load, not on
navigation.
Closes #57.
> asset list: display institutions using their lookup name

- src/components/LogoutLink.js
- src/redux/reducers/index.js
- src/redux/reducers/index.test.js
LOGOUT is a special action in that potentially all state cached by the application becomes invalid.
Wrap the default reducer in an implementation which resets state by calling the reducers with undefined as the current state. Reducers are given a change to "save" something from the original state since it is added to the LOGOUT action as an originalState property but a "naive" reducer will just return the initial state for the application.
Closes #74
> reset all application state on logout

- src/containers/App.js
Add REACT_APP_BASENAME configuration which allows configuring the basename under which the app is served.
This is passed directly through to the BrowserRouter component. If changing from the default value of "/", ensure that it has a tailing and leading slash.
> allow react router basename to be configured via environment variable

- README.md
- src/redux/actions/auth.js
The OAuth2 redirect URL was constructed with no regard to basename.
Allow it to be overridden via a setting. If the setting is not provided,
it is constructed.
> add REACT_APP_OAUTH_REDIRECT setting for configuring Oauth2 redirect URL

- src/index.js
As noted in #91, the service worker we register in index.js provides an additional level of offline caching for the application. This provides very rapid load times on, e.g., Google Chrome but has the downside that updates to the application may take 24 hours to propagate.
While we still may make lock-step backend/frontend changes, disable and un-register (if registered) the service worker. We can re-visit this once the application stabilises.
Closes #91.
> src/index.js: un register the service worker

- src/containers/AssetList.js
This is a little hack to expose the search functionality by a "hidden" URL parameter on the asset entry list pages.
If "?q=[...]" is appended to the URL, the value is passed to the backend as the "search" parameter.
This is intended a) to make it easy to evaluate the search functionality and b) to aid UX in finding and evaluating usages of the IAR.
> HACK: allow searching through "secret" ?q=[...] URL

- src/AssetDetail/presentational/AssetForm.js
- src/containers/PreventNavigationWhenDraftModified.js
- src/draft/draft.test.js
- src/redux/actions/editAsset.js
- src/redux/actions/editAsset.test.js
- src/redux/reducers/editAsset.js
- src/redux/reducers/editAsset.test.js
This PR implements changes required to address #62.
* 44fd400 adds support for tracking the "modified" state of the current draft entry
* 7f0931f resets the modified state on successful save
* 612afbb adds a new component which monitors the "modified" flag and prevents navigation from in-process entries
Closes #62.
> request confirmation when navigating away from an unsaved entry

- src/components/AssetListHeader.js
- src/components/Sidebar.js
- src/components/SidebarNavLink.js
- src/containers/Page.js
- src/style/CustomMaterialTheme.js
**Opening a PR here so we can review the architecture. Once agreed I can make my way through various pages/components and make them fluid/responsive.**
For screen-widths of 960px and under, the sidebar should shrink in width and decrease the font-size of the list items.
The theme file holds the values, which are imported via `withStyles` like usual, and the component itself holds the breakpoint logic to apply the styles.
We use the material-ui way of breakpoints, instead of manually applying media queries, for example `@media (min-width: 1px)`. [More info here](https://material-ui-next.com/layout/css-in-js/#theme-breakpoints-up-key-media-query)
> First stab at responsive elements using JSS and theme file

- src/components/CheckIsUser.js
- src/components/FetchSelf.js
- src/containers/AssetList.js
- src/containers/AssetList.test.js
Refactored AssetList to only get new assets if the new query doesn't match the old (was sort of doing that before but now does it better). Also use componentDidUpdate instead of componentWillReceiveProps to
avoid fetching same assets twice.
closes: #115
> Only get assets if query different from state.

- .env
- .gitignore
- README.md
- public/index.html
- src/AssetDetail/containers/FetchAsset.js
- src/AssetDetail/containers/FetchOrCreateDraft.js
- src/AssetDetail/presentational/AssetView.test.js
- src/components/CheckIsUser.js
- src/config.js
- src/containers/App.js
- src/containers/AppRoutes.test.js
- src/redux/actions/assetRegisterApi.js
- src/redux/actions/assetRegisterApi.test.js
- src/redux/actions/auth.js
- src/redux/actions/lookupApi.js
- src/test/config.js
- src/test/fixtures.js
- src/test/mocks.js
- templates/config.in.js
Application configuration via .env files had the advantage that the configuration was baked into the production app at npm build time. This was also a disadvantage since some configuration differes between releases (test, production, etc) and we'd like to use the same application image to serve them if possible.
Move existing uses of the REACT_APP_... environment variables over to a new configuration object which is initialised at runtime and may be overridden both locally in development and in production by adding a line to index.html. See the README.md changes for more details.
For the test suite, there is no browser and index.html is not loaded. In this case the configuration is loaded from the default export of the src/test/config.js module instead.
To use the configuration mechanism, …
> replace build-time .env configuration with run-time config.js file

- src/redux/actions/editAsset.js
- src/redux/actions/editAsset.test.js
Currently, saving a draft entry with a blank institution will result in a HTTP 400 error being displayed to the user. Instead, catch the source of this error at saveDraft() time and warn the user instead.
> do not save draft is institution is blank

- src/components/FetchLookupInstitutions.js
- src/components/FetchSelf.js
- src/redux/reducers/lookupApi.js
- src/redux/reducers/lookupApi.test.js
> **Testing notes:** in order to show the problem this PR addresses, one needs to arrange for the lookupproxy to fail. This can be done by downloading a little test script, [corsdevserver.py](https://gist.github.com/rjw57/4a1037d71d9fe42673ed0b2d6c68b929) which can replace the lookupproxy. Run via: ``docker-compose stop lookupproxy && python2 corsdevserver.py``. Without this PR applied, the browser should get stuck in a reload loop for the user's profile.
As noted in #77, if fetching the user's profile fails, we get stuck in a loop where the browser tries again and again, hammering the browser.
For both the user's profile and the list of instututions, record a "requestedAt" date which records when the last request was in flight. We then only try to load the corresponding resource if:
1. …
> only try to fetch institutions list and "self" once

- src/components/AssetTableBody.js
- src/components/AssetTableHeader.js
- src/components/GetMoreAssets.js
- src/containers/LoadingIndicator.js
- src/redux/actions/assetRegisterApi.js
- src/redux/reducers/assetRegisterApi.js
- src/redux/reducers/assetRegisterApi.test.js
**Reviewers' note:** this PR is best reviewed commit-wise.
This PR implements some strategies to provide feedback to users when the asset entry table is being refreshed. See #146 for more information. The following three stragegies are employed:
1. When fetching a *new* asset entry list (not simply extending the existing one) the asset list fades out to be replaced with the new one. When extending the asset entry list, the existing behaviour of simply appending to the list is used.
2. When fetching an asset list, a linear progress indicator is added below the asset entry table header. This provides immediate visual feedback to users that a load is happening.
3. To avoid over egging the pudding w.r.t. loading indicators, the circular loading indicator at the bottom of the asset table is …
> Provide indication when loading asset entries into the list

- src/AssetDetail/presentational/GeneralInformationFields.js
- src/AssetDetail/presentational/RiskFields.js
- src/AssetDetail/presentational/StorageAndSecurityFields.js
The backend requires that text input be less than 255 characters but nothing on the frontend mandates this. As a hack, limit all text fields to 240 characters.
We need to revisit this later for a better solution.
This issue is being hit by users in the wild.
> hack: limit length of text input

- compose/hydra.env
- package-lock.json
- package.json
- public/oauth2-callback.html
- scripts/create-client.sh
- src/auth.js
- src/config.js
- src/containers/App.js
- src/containers/AppRoutes.js
- src/containers/TokenTimeout.js
- src/redux/actions/auth.js
- src/redux/actions/auth.test.js
- src/redux/enhancer.js
- src/redux/reducers/auth.js
- src/redux/reducers/auth.test.js
- src/redux/reducers/index.js
- src/redux/reducers/index.test.js
- src/redux/reducers/snackbar.js
- src/test/mock-localstorage.js
This PR addresses #98 and has the following dependent PRs:
* uisautomation/hydra-consent-app#5
* uisautomation/experimental-mock-consent-app#2
* uisautomation/iar-deploy#31
It is quite a large PR and is best reviewed commit-wise since most commits have somewhat involved comments.
The main body of the PR is composed of two commits, 6c6e3af and 5dc698e.
6c6e3af replaces our existing use of ``redux-implicit-oauth2`` with our own version of implicit OAuth2 flow (implemented in 86ecd15) which distinguishes between normal and "promptless" logins. The latter logins do not require a popup window but may fail.
5dc698e makes use of the new OAuth2 login implemented by 6c6e3af in order to provide a nicer UX on token timeout. See that commit's comment for more information. The commit itself includes …
> Improve token timeout behaviour
